site_name: e.c. humphry
site_url: https://evahhumphry.com/mysite
theme:
  features:
    - navigation.tabs
    - navigation.indexes
  name: material 
  palette:
    scheme: slate
    primary: blue
    accent: deep purple
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - blog
